return {
	"williamboman/mason-lspconfig.nvim",
	dependencies = {
		"neovim/nvim-lspconfig",
		"williamboman/mason.nvim",
	},
	event = { "BufRead" },
	opts = {
		ensure_installed = {
			"bashls",
			"cssls",
			"docker_compose_language_service",
			"dockerls",
			"emmet_ls",
			"eslint",
			"gopls",
			"graphql",
			"harper_ls",
			"html",
			"jsonls",
			"lua_ls",
			"pyright",
			"sqls",
			"tsserver",
			"vimls",
			"yamlls",
		},
		automatic_installation = true,
	},
}
